# Generated by Django 5.2.9 on 2026-07-08 12:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GrupaNaglowek",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa", models.CharField(max_length=255, unique=True)),
                ("data_utworzenia", models.DateField(auto_now_add=True)),
                (
                    "utworzone_przez_uzytkownika",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("data_od", models.DateField(default=datetime.date.today)),
                ("data_do", models.DateField(default=datetime.date(9999, 12, 31))),
            ],
            options={
                "ordering": ["nazwa"],
            },
        ),
        migrations.CreateModel(
            name="Obszar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kod", models.CharField(max_length=10, unique=True)),
                ("nazwa", models.CharField(max_length=100, unique=True)),
                ("data_utworzenia", models.DateTimeField(auto_now_add=True)),
                (
                    "utworzone_przez_uzytkownika",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "ordering": ["kod"],
            },
        ),
        migrations.CreateModel(
            name="OkresSprawozdawczy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rok",
                    models.IntegerField(unique=True, verbose_name="Rok sprawozdawczy"),
                ),
                (
                    "czy_zamrozony",
                    models.BooleanField(
                        default=False, verbose_name="Czy opublikowany/zamrożony?"
                    ),
                ),
            ],
            options={
                "ordering": ["-rok"],
            },
        ),
        migrations.CreateModel(
            name="Podmiot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kod", models.CharField(max_length=10, unique=True)),
                ("nazwa", models.CharField(max_length=300)),
                ("data_utworzenia", models.DateTimeField(auto_now_add=True)),
                (
                    "utworzone_przez_uzytkownika",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "ordering": ["kod"],
            },
        ),
        migrations.CreateModel(
            name="Podzapytanie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kod", models.CharField(max_length=20)),
                ("tresc", models.CharField(max_length=700)),
                ("obligatoryjne", models.BooleanField(default=True)),
                ("wytyczne", models.CharField(max_length=700)),
                ("data_utworzenia", models.DateTimeField(auto_now_add=True)),
                (
                    "utworzone_przez_uzytkownika",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("data_od", models.DateField()),
                ("data_do", models.DateField()),
            ],
            options={
                "ordering": ["kod"],
            },
        ),
        migrations.CreateModel(
            name="Slownik",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa", models.CharField(max_length=100, unique=True)),
                ("opcje", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="Blok",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kod", models.CharField(max_length=20)),
                ("tresc", models.CharField(max_length=300)),
                (
                    "utworzone_przez_uzytkownika",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("data_od", models.DateField(default=datetime.date.today)),
                ("data_do", models.DateField(default=datetime.date(9999, 12, 31))),
                ("data_utworzenia", models.DateTimeField(auto_now_add=True)),
                (
                    "id_obszaru",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bloki",
                        to="fossa2.obszar",
                    ),
                ),
            ],
            options={
                "ordering": ["kod", "-data_od"],
            },
        ),
        migrations.CreateModel(
            name="AnkietaNaglowek",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa", models.CharField(max_length=100, unique=True)),
                ("data_utworzenia", models.DateTimeField(auto_now_add=True)),
                (
                    "utworzone_przez_uzytkownika",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("data_od", models.DateField(default=datetime.date.today)),
                ("data_do", models.DateField(default=datetime.date(9999, 12, 31))),
                ("kod_obszaru_snapshot", models.CharField(max_length=10)),
                (
                    "id_grupa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fossa2.grupanaglowek",
                    ),
                ),
                (
                    "id_obszar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="fossa2.obszar",
                    ),
                ),
            ],
            options={
                "ordering": ["nazwa"],
            },
        ),
        migrations.CreateModel(
            name="Podblok",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kod", models.CharField(max_length=20)),
                ("tresc", models.CharField(max_length=300)),
                (
                    "utworzone_przez_uzytkownika",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("data_od", models.DateField(default=datetime.date.today)),
                ("data_do", models.DateField(default=datetime.date(9999, 12, 31))),
                ("data_utworzenia", models.DateTimeField(auto_now_add=True)),
                (
                    "id_bloku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="podbloki",
                        to="fossa2.blok",
                    ),
                ),
            ],
            options={
                "ordering": ["kod"],
            },
        ),
        migrations.CreateModel(
            name="GrupaPodmioty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_utworzenia", models.DateTimeField(auto_now_add=True)),
                (
                    "utworzone_przez_uzytkownika",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("data_od", models.DateField(default=datetime.date.today)),
                ("data_do", models.DateField(default=datetime.date(9999, 12, 31))),
                ("nazwa_podmiotu_snapshot", models.CharField(max_length=10)),
                (
                    "id_grupa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fossa2.grupanaglowek",
                    ),
                ),
                (
                    "id_podmiotu",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="fossa2.podmiot",
                    ),
                ),
            ],
            options={
                "ordering": ["id_podmiotu"],
            },
        ),
        migrations.CreateModel(
            name="AnkietaPytania",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_utworzenia", models.DateTimeField(auto_now_add=True)),
                (
                    "utworzone_przez_uzytkownika",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "id_ankieta_naglowek",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fossa2.ankietanaglowek",
                    ),
                ),
                (
                    "id_podzapytania",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fossa2.podzapytanie",
                    ),
                ),
            ],
            options={
                "ordering": ["id_ankieta_naglowek", "id_podzapytania"],
            },
        ),
        migrations.CreateModel(
            name="Pytanie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kod", models.CharField(max_length=20)),
                ("tresc", models.CharField(max_length=700)),
                ("data_utworzenia", models.DateTimeField(auto_now_add=True)),
                (
                    "utworzone_przez_uzytkownika",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("data_od", models.DateField()),
                ("data_do", models.DateField()),
                (
                    "id_podbloku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pytania",
                        to="fossa2.podblok",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="podzapytanie",
            name="id_pytania",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="podzapytania",
                to="fossa2.pytanie",
            ),
        ),
        migrations.AddField(
            model_name="podzapytanie",
            name="slownik",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="podzapytania",
                to="fossa2.slownik",
            ),
        ),
    ]
